version: '3.1'

services:
  mailcatcher:
    image: schickling/mailcatcher:latest
    ports:
      - 1080:1080
      - 1025:1025

  db:
    image: postgres:9.6-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres

  redis:
    image: redis:alpine3.11
    ports:
      - 6379:6379
