default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  username: <%= ENV.fetch('POSTGRES_USERNAME') { 'postgres' } %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD') { 'postgres' } %>
  host: localhost
  port: 5432

development:
  <<: *default
  database: covid_sc_development

test:
  <<: *default
  timeout: 5000
  database: covid_sc_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
