default: &default
  adapter: postgresql
  encoding: unicode
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>

development:
  <<: *default
  database: covid_sc_development
  username: postgres
  password: postgres
  host: localhost
  port: 5432

test:
  <<: *default
  encoding: utf8
  host: localhost
  timeout: 5000
  database: covid_sc_test

production:
  <<: *default
  database: covid_sc_production
  username: covid_sc
  password: postgres
